---
title: "Calibration"
author: "Ben Bond-Lamberty"
date: "`r Sys.Date()`"
output: html_document
---

# Calibrate Hector parameters against historical observations

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readr)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
library(tidyr)

# Read in ini file, initiate new core
library(hector)
if(packageVersion("hector") != '3.0.0') stop("unexpected verrsion of hector")

LOGDIR <- here::here("workflow", "L0.logs")
dir.create(LOGDIR, showWarnings = FALSE, recursive = TRUE)

DATADIR <- here::here("data")

LOGFILE <- file.path(LOGDIR, "optim_logfile.csv")
unlink(LOGFILE)
CO2LOGFILE <- file.path(LOGDIR, "optim_logfile_co2.csv")
unlink(CO2LOGFILE)
```


```{r}
ssp245 <- system.file("input/hector_ssp245.ini", package = "hector")
core <- newcore(ssp245)

# Define name and units of all parameters
name_vector <- c("BETA" = BETA(), "Q10_RH" = Q10_RH(),
                 "ECS" = ECS(), "NPP_FLUX0" = NPP_FLUX0(),
                 "AERO_SCALE" = AERO_SCALE(), "DIFFUSIVITY" = DIFFUSIVITY(),
                 "LUC_SCALAR" = "LUC_SCALAR"
)

units_vector <- c("BETA" = "(unitless)", "Q10_RH" = "(unitless)",
                  "ECS" = "degC", "NPP_FLUX0" = "Pg C/yr",
                  "AERO_SCALE" = "(unitless)", "DIFFUSIVITY" = "cm2/s",
                  "LUC_SCALAR" = "(unitless)"
)
```


```{r observations}
# Mauna Loa CO2 - downloaded 2022-05-05 from https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_annmean_mlo.csv
# R actually has this as a built-in dataset but it stops at 1997! Too bad
read_csv(file.path(DATADIR, "co2_annmean_mlo.csv"), col_types = "ddd", comment = "#") %>% 
  rename(value = mean) %>% 
  mutate(which = "Mauna Loa") ->
  OBSERVED_CO2

# NASA GISS temperature - downloaded 2020-05-06 from https://climate.nasa.gov/vital-signs/global-temperature/
OBSERVED_TAS <- read_table(file.path(DATADIR, "giss_temperature.txt"), skip = 5,
                           col_names = c("year", "value"),
                           col_types = "dd-")
OBSERVED_TAS$which <- "NASA GISS"
```

```{r parameters}
# Initial starting values are:
params <- c("BETA" = fetchvars(core, NA, BETA())$value,
            "Q10_RH" = fetchvars(core, NA, Q10_RH())$value,
            "NPP_FLUX0" = fetchvars(core, NA, NPP_FLUX0())$value,
            "AERO_SCALE" = fetchvars(core, NA, AERO_SCALE())$value,
            "ECS" = fetchvars(core, NA, ECS())$value,
            "DIFFUSIVITY" = fetchvars(core, NA, DIFFUSIVITY())$value)

# Standard deviations are based on Leeya's research and code
# https://github.com/JGCRI/trackingC/blob/main/trackingC_setup.Rmd
params_sd <- c("BETA" = 0.2,
               "Q10_RH" = 0.6,
               "NPP_FLUX0" = 14,
               "AERO_SCALE" = 0.5,
               "ECS" = 1.0,
               "DIFFUSIVITY" = 0.23)
params_lower <- params - params_sd
params_upper <- params + params_sd
# Actually AERO_SCALE can't go above 1 or below 0 
params_upper["AERO_SCALE"] <- 1.0
params_lower["AERO_SCALE"] <- 0
```

```{r optim-functions}
set_params <- function(params, core) {
  # For each parameter within each run, set its value and units
  if(!step %% 10) message(step, " ", Sys.time())
  for(p in names(params)) {
    # If the parameter is a scaling constant, multiply and set scaled values
    if(p == "LUC_SCALAR") {
      setvar(core, luc$year, LUC_EMISSIONS(), (luc$value * params[p]), "Pg C/yr")
    } else {
      # Otherwise, simply set the value of the parameter itself
      setvar(core, NA, do.call(p, list()), params[p], units_vector[p])
    }
  }
}

run_hector <- function(params, core, log = TRUE) {
  # params is a named vector of parameters
  # core is a Hector core
  step <<- step + 1
  set_params(params, core)
  
  # Reset and run core
  reset(core)
  run(core, runtodate = max(OBSERVED_CO2$year))
  
  # Get atmospheric [CO2] and compare to observational record
  # We use normalized sum of squares so entire time series is weighted equally
  co2 <- fetchvars(core, OBSERVED_CO2$year, CONCENTRATIONS_CO2())
  nss <- sum(((OBSERVED_CO2$value - co2$value) ^ 2) / OBSERVED_CO2$value)
  
  # Log
  if(log) {
    co2$step <- step
    write_csv(co2, CO2LOGFILE, append = TRUE, col_names = !file.exists(CO2LOGFILE))
    params_df <- as.data.frame(t(as.data.frame(params)))
    params_df$NSS <- nss
    params_df$step <- step
    write_csv(params_df, LOGFILE, append = TRUE, col_names = !file.exists(LOGFILE))
  }
  
  # Return normalized sum of squares to optimizer
  return(nss)
}
```

## Calibration

```{r optimize, cache=TRUE, message=FALSE}
step <- 0
start <- Sys.time()
result <- optim(params, run_hector, gr = NULL, core,
                method = "L-BFGS-B",
                lower = params_lower,
                upper = params_upper)
end <- Sys.time()
shutdown(core)
time_taken <- difftime(end, start, units = "mins")
```

Calibration took `r round(time_taken, 1)` minutes.

## Result

```{r}
print(result)
```

## Parameter changes

```{r param-changes}
param_results <- readr::read_csv(LOGFILE, col_types = "dddddddd")
param_results %>%
  pivot_longer(-step) %>%
  ggplot(aes(step, value)) + geom_line() +
  facet_wrap(~name, scales = "free_y")

params_tab <- tibble(Parameter = names(params),
                     `Start value` = params,
                     `Low bound` = params_lower,
                     `High bound` = params_upper,
                     `Final value` = result$par)
knitr::kable(params_tab)


write_csv(params_tab, file = file.path(LOGDIR, "params_table.csv"))


param_fits <- t(data.frame(params_tab$`Final value`))
write.csv(param_fits, file = file.path(DATADIR, "calibration_param_fits.csv"), row.names = FALSE)
```


```{r run-default-optim, include=FALSE}
# Brand new core, run default and optimized
core <- newcore(ssp245)
suppressMessages(run(core))
out1 <- fetchvars(core, core$strtdate:core$enddate)
out1$which <- "Default"
set_params(result$par, core)
reset(core)
suppressMessages(run(core))
out2 <- fetchvars(core, core$strtdate:core$enddate)
out2$which <- "Optimized"
out <- rbind(out1, out2)
```

## Observations

```{r comparison}
# Compare to observed CO2
out %>%
  filter(variable == CONCENTRATIONS_CO2()) %>% 
  select(year, value, which) %>% 
  bind_rows(OBSERVED_CO2)  %>%
  filter(year %in% OBSERVED_CO2$year)  %>% 
  ggplot(aes(year, value, color = which)) +
  geom_line() + 
  ggtitle("CO2 (optimized against)") + scale_color_discrete("")

# Compare to observed temperature
tas <- filter(out, variable == GLOBAL_TAS())
tas %>%
  select(year, value, which) %>% 
  # renormalize to 1951-1980 mean, to match GISS
  filter(year %in% 1951:1980) %>%
  group_by(which) %>%
  summarise(mean19511980 = mean(value)) %>%
  right_join(tas, by = "which") %>%
  mutate(value = value - mean19511980) %>%
  select(-mean19511980) %>%
  bind_rows(OBSERVED_TAS)  %>%
  filter(year %in% OBSERVED_TAS$year) ->
  tas_combined

ggplot(tas_combined, aes(year, value, color = which)) +
  geom_line() + 
  ggtitle("Air temperature (not optimized against)") + scale_color_discrete("")
```

## Future

```{r}
# Plot all data for four main outputs
ggplot(out, aes(year, value, color = which)) +
  geom_line() +
  facet_wrap(~variable, scales = "free") +
  scale_color_discrete("")
```

# The End

```{r the-end}
shutdown(core)
sessionInfo()
```
